name: Buamtech CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn -B -f backend/pom.xml clean package

      - name: Build Docker Image
        run: docker build -t buamtech/backend:latest backend/

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buamtech-backend-jar
          path: backend/target/*.jar
